# Generated by Django 5.0.14 on 2026-07-02 20:37
"""Migración inicial para el proyecto Rassa.

Crea las 32 tablas del dominio de negocio:
- Catálogos base (roles, categorías, unidades, estados)
- Identidad (persona, usuario)
- Agrupaciones (familias, límites)
- Productos (catálogo, publicaciones semanales)
- Operaciones (pedidos, pagos, mermas, cortes)
- Comunicación (chat, mensajes)
- Auditoría (logs)
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoriaProducto",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.CharField(max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "categoria_producto",
                "ordering": ["id_categoria"],
            },
        ),
        migrations.CreateModel(
            name="Conversacion",
            fields=[
                (
                    "id_conversacion",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
                ("tipo", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "conversacion",
                "ordering": ["id_conversacion"],
            },
        ),
        migrations.CreateModel(
            name="Corte",
            fields=[
                ("id_corte", models.AutoField(primary_key=True, serialize=False)),
                ("monto_real", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monto_teorico", models.DecimalField(decimal_places=2, max_digits=10)),
                ("diferencia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("cerrado", "Cerrado"),
                            ("cuadrado", "Cuadrado"),
                        ],
                        default="abierto",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "corte",
                "ordering": ["id_corte"],
            },
        ),
        migrations.CreateModel(
            name="DecisionMerma",
            fields=[
                ("id_decision", models.AutoField(primary_key=True, serialize=False)),
                ("decision", models.CharField(max_length=50)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "decision_merma",
                "ordering": ["id_decision"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                ("id_documento", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_documento", models.CharField(max_length=100)),
                ("url_documento", models.TextField()),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("imagen", "Imagen"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                        ],
                        max_length=50,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "documento",
                "ordering": ["id_documento"],
            },
        ),
        migrations.CreateModel(
            name="EstadoPedido",
            fields=[
                ("id_estado", models.AutoField(primary_key=True, serialize=False)),
                ("tipo_estado", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "estado_pedido",
                "ordering": ["id_estado"],
            },
        ),
        migrations.CreateModel(
            name="Familia",
            fields=[
                ("id_familia", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_familia", models.CharField(max_length=100)),
                (
                    "detalle_familia",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "familia",
                "ordering": ["id_familia"],
            },
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                ("id_municipio", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "municipio",
                "ordering": ["id_municipio"],
            },
        ),
        migrations.CreateModel(
            name="PublicacionSemanal",
            fields=[
                ("id_publicacion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_publicacion", models.DateField()),
                ("semana", models.PositiveIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicado", "Publicado"),
                            ("cerrado", "Cerrado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "publicacion_semanal",
                "ordering": ["id_publicacion"],
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                ("id_rol", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_rol", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.CharField(max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "roles",
                "ordering": ["id_rol"],
            },
        ),
        migrations.CreateModel(
            name="TipoPago",
            fields=[
                ("id_tipo_pago", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30, unique=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tipo_pago",
                "ordering": ["id_tipo_pago"],
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                ("id_unidad", models.AutoField(primary_key=True, serialize=False)),
                ("tipo", models.CharField(max_length=50)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "unidad",
                "ordering": ["id_unidad"],
            },
        ),
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                ("id_mensaje", models.AutoField(primary_key=True, serialize=False)),
                ("contenido", models.TextField(blank=True, null=True)),
                ("leido", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_conversacion",
                    models.ForeignKey(
                        db_column="fk_conversacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.conversacion",
                    ),
                ),
            ],
            options={
                "db_table": "mensaje",
                "ordering": ["id_mensaje"],
            },
        ),
        migrations.CreateModel(
            name="MensajeDocumento",
            fields=[
                (
                    "id_mensaje_documento",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_documento",
                    models.ForeignKey(
                        db_column="fk_documento",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.documento",
                    ),
                ),
                (
                    "fk_mensaje",
                    models.ForeignKey(
                        db_column="fk_mensaje",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.mensaje",
                    ),
                ),
            ],
            options={
                "db_table": "mensajes_documentos",
                "ordering": ["id_mensaje_documento"],
            },
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                ("id_localidad", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=150)),
                (
                    "fk_municipio",
                    models.ForeignKey(
                        db_column="fk_municipio",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.municipio",
                    ),
                ),
            ],
            options={
                "db_table": "localidad",
                "ordering": ["id_localidad"],
            },
        ),
        migrations.CreateModel(
            name="PedidoCabecera",
            fields=[
                ("id_pedido", models.AutoField(primary_key=True, serialize=False)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("iva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_expiracion", models.DateTimeField(blank=True, null=True)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_estado",
                    models.ForeignKey(
                        db_column="fk_estado",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.estadopedido",
                    ),
                ),
            ],
            options={
                "db_table": "pedido_cabecera",
                "ordering": ["id_pedido"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                ("id_pago", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("referencia", models.CharField(blank=True, max_length=100, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_pedido",
                    models.ForeignKey(
                        db_column="fk_pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.pedidocabecera",
                    ),
                ),
                (
                    "fk_tipo",
                    models.ForeignKey(
                        db_column="fk_tipo",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.tipopago",
                    ),
                ),
            ],
            options={
                "db_table": "pago",
                "ordering": ["id_pago"],
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                ("id_persona", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido_paterno", models.CharField(max_length=100)),
                (
                    "apellido_materno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fecha_nacimiento", models.DateField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("domicilio", models.CharField(max_length=300)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_localidad",
                    models.ForeignKey(
                        blank=True,
                        db_column="fk_localidad",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rassa.localidad",
                    ),
                ),
            ],
            options={
                "db_table": "persona",
                "ordering": ["id_persona"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id_producto", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_producto", models.CharField(max_length=150)),
                ("es_perecedero", models.BooleanField(default=False)),
                ("estado", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_categoria",
                    models.ForeignKey(
                        db_column="fk_categoria",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.categoriaproducto",
                    ),
                ),
            ],
            options={
                "db_table": "producto",
                "ordering": ["id_producto"],
            },
        ),
        migrations.CreateModel(
            name="ProductoImagen",
            fields=[
                ("id_imagen", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.TextField()),
                ("es_principal", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_producto",
                    models.ForeignKey(
                        db_column="fk_producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.producto",
                    ),
                ),
            ],
            options={
                "db_table": "producto_imagen",
                "ordering": ["id_imagen"],
            },
        ),
        migrations.CreateModel(
            name="ProductoSemanal",
            fields=[
                (
                    "id_producto_semanal",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("stock", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("foto", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("activo", "Activo"), ("inactivo", "Inactivo")],
                        default="activo",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_producto",
                    models.ForeignKey(
                        db_column="fk_producto",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.producto",
                    ),
                ),
                (
                    "fk_publicacion",
                    models.ForeignKey(
                        db_column="fk_publicacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.publicacionsemanal",
                    ),
                ),
                (
                    "fk_unidad",
                    models.ForeignKey(
                        db_column="fk_unidad",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.unidad",
                    ),
                ),
            ],
            options={
                "db_table": "producto_semanal",
                "ordering": ["id_producto_semanal"],
            },
        ),
        migrations.CreateModel(
            name="Merma",
            fields=[
                ("id_merma", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.PositiveIntegerField()),
                ("motivo", models.CharField(max_length=300)),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_decision",
                    models.ForeignKey(
                        db_column="fk_decision",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.decisionmerma",
                    ),
                ),
                (
                    "fk_producto_semanal",
                    models.ForeignKey(
                        db_column="fk_producto_semanal",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.productosemanal",
                    ),
                ),
            ],
            options={
                "db_table": "merma",
                "ordering": ["id_merma"],
            },
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                ("id_detalle", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_producto", models.CharField(max_length=150)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("importe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_pedido",
                    models.ForeignKey(
                        db_column="fk_pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.pedidocabecera",
                    ),
                ),
                (
                    "fk_producto_semanal",
                    models.ForeignKey(
                        db_column="fk_producto_semanal",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.productosemanal",
                    ),
                ),
            ],
            options={
                "db_table": "detalle_pedido",
                "ordering": ["id_detalle"],
            },
        ),
        migrations.CreateModel(
            name="Recibo",
            fields=[
                ("id_recibo", models.AutoField(primary_key=True, serialize=False)),
                ("folio", models.CharField(max_length=50, unique=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_pago",
                    models.ForeignKey(
                        db_column="fk_pago",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.pago",
                    ),
                ),
                (
                    "fk_pedido",
                    models.ForeignKey(
                        db_column="fk_pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.pedidocabecera",
                    ),
                ),
            ],
            options={
                "db_table": "recibo",
                "ordering": ["id_recibo"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("telefono", models.CharField(max_length=15)),
                ("contrasenia", models.CharField(max_length=255)),
                ("correo", models.CharField(max_length=150, unique=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_persona",
                    models.OneToOneField(
                        db_column="fk_persona",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.persona",
                    ),
                ),
                (
                    "fk_rol",
                    models.ForeignKey(
                        db_column="fk_rol",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.rol",
                    ),
                ),
            ],
            options={
                "db_table": "usuario",
                "ordering": ["id_usuario"],
            },
        ),
        migrations.CreateModel(
            name="Recoleccion",
            fields=[
                ("id_recoleccion", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_recoleccion", models.DateField()),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_ruta", "En Ruta"),
                            ("recolectado", "Recolectado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("comentarios", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_agricultor",
                    models.ForeignKey(
                        db_column="fk_agricultor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "recoleccion",
                "ordering": ["id_recoleccion"],
            },
        ),
        migrations.AddField(
            model_name="publicacionsemanal",
            name="fk_agricultor",
            field=models.ForeignKey(
                db_column="fk_agricultor",
                on_delete=django.db.models.deletion.CASCADE,
                to="rassa.usuario",
            ),
        ),
        migrations.AddField(
            model_name="pedidocabecera",
            name="fk_cliente",
            field=models.ForeignKey(
                db_column="fk_cliente",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos_como_cliente",
                to="rassa.usuario",
            ),
        ),
        migrations.AddField(
            model_name="pedidocabecera",
            name="fk_vendedor",
            field=models.ForeignKey(
                blank=True,
                db_column="fk_vendedor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pedidos_como_vendedor",
                to="rassa.usuario",
            ),
        ),
        migrations.AddField(
            model_name="mensaje",
            name="fk_emisor",
            field=models.ForeignKey(
                db_column="fk_emisor",
                on_delete=django.db.models.deletion.CASCADE,
                to="rassa.usuario",
            ),
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                ("id_log", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField()),
                ("ip", models.GenericIPAddressField()),
                ("dispositivo", models.CharField(max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_usuario",
                    models.ForeignKey(
                        db_column="fk_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "logs",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Liquidacion",
            fields=[
                ("id_liquidacion", models.AutoField(primary_key=True, serialize=False)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("monto_ventas", models.DecimalField(decimal_places=2, max_digits=10)),
                ("comision", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monto_liquidar",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagada", "Pagada"),
                            ("parcial", "Parcial"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_pago_liquidacion",
                    models.ForeignKey(
                        blank=True,
                        db_column="fk_pago_liquidacion",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rassa.pago",
                    ),
                ),
                (
                    "fk_agricultor",
                    models.ForeignKey(
                        db_column="fk_agricultor",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "liquidacion",
                "ordering": ["id_liquidacion"],
            },
        ),
        migrations.CreateModel(
            name="LimiteCliente",
            fields=[
                ("id_limite", models.AutoField(primary_key=True, serialize=False)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_usuario",
                    models.OneToOneField(
                        db_column="fk_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "limite_cliente",
                "ordering": ["id_limite"],
            },
        ),
        migrations.CreateModel(
            name="Integrante",
            fields=[
                ("id_miembro", models.AutoField(primary_key=True, serialize=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_conversacion",
                    models.ForeignKey(
                        db_column="fk_conversacion",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.conversacion",
                    ),
                ),
                (
                    "fk_usuario",
                    models.ForeignKey(
                        db_column="fk_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "integrantes",
                "ordering": ["id_miembro"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoPedido",
            fields=[
                ("id_historial", models.AutoField(primary_key=True, serialize=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_estado_anterior",
                    models.ForeignKey(
                        blank=True,
                        db_column="fk_estado_anterior",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historial_anterior",
                        to="rassa.estadopedido",
                    ),
                ),
                (
                    "fk_estado_nuevo",
                    models.ForeignKey(
                        db_column="fk_estado_nuevo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_nuevo",
                        to="rassa.estadopedido",
                    ),
                ),
                (
                    "fk_pedido",
                    models.ForeignKey(
                        db_column="fk_pedido",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.pedidocabecera",
                    ),
                ),
                (
                    "fk_cambiado_por",
                    models.ForeignKey(
                        db_column="fk_cambiado_por",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "historial_estado_pedido",
                "ordering": ["id_historial"],
            },
        ),
        migrations.CreateModel(
            name="FamiliaUsuario",
            fields=[
                (
                    "id_familia_usuario",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("estado", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "fk_familia",
                    models.ForeignKey(
                        db_column="fk_familia",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.familia",
                    ),
                ),
                (
                    "fk_usuario",
                    models.OneToOneField(
                        db_column="fk_usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rassa.usuario",
                    ),
                ),
            ],
            options={
                "db_table": "familia_usuario",
                "ordering": ["id_familia_usuario"],
            },
        ),
        migrations.AddField(
            model_name="familia",
            name="fk_jefe_familia",
            field=models.ForeignKey(
                db_column="fk_jefe_familia",
                on_delete=django.db.models.deletion.CASCADE,
                to="rassa.usuario",
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="fk_usuario",
            field=models.ForeignKey(
                db_column="fk_usuario",
                on_delete=django.db.models.deletion.CASCADE,
                to="rassa.usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="mensajedocumento",
            constraint=models.UniqueConstraint(
                fields=("fk_mensaje", "fk_documento"), name="unique_mensaje_documento"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicacionsemanal",
            constraint=models.CheckConstraint(
                check=models.Q(("semana__gte", 1), ("semana__lte", 52)),
                name="check_semana_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="integrante",
            constraint=models.UniqueConstraint(
                fields=("fk_usuario", "fk_conversacion"),
                name="unique_integrante_usuario_conversacion",
            ),
        ),
    ]
