# Generated by Django 5.0.14 on 2026-07-02 23:40

from django.db import migrations


class Migration(migrations.Migration):
    """La autenticación se realiza mediante django.contrib.auth.models.User
    (tabla auth_user).
    Por lo tanto, se elimina el campo contrasenia del modelo Usuario.
    """

    dependencies = [
        ("rassa", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="contrasenia",
        ),
    ]
