# Generated by Django 5.0.14 on 2026-07-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0002_remove_usuario_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rassa.usuario'),
        ),
    ]
