# Generated by Django 5.0.14 on 2026-07-03 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rassa", "0004_usuario_add_fk_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="fk_user",
            field=models.OneToOneField(
                blank=True,
                db_column="fk_user",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
