# Generated by Django 5.0.14 on 2026-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0006_cascade_to_set_null_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
