# Generated by Django 5.0.14 on 2026-07-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0006_cascade_to_set_null_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
