# Generated by Django 5.0.14 on 2026-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0006_cascade_to_set_null_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
