# Generated by Django 5.0.14 on 2026-07-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0007_reconcile_squash_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='eliminar_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
