# Generated by Django 5.0.14 on 2026-07-11 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0007_add_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fk_unidad',
            field=models.ForeignKey(blank=True, db_column='fk_unidad', null=True, on_delete=django.db.models.deletion.PROTECT, to='rassa.unidad'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
