# Generated by Django 5.0.14 on 2026-07-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0008_backfill_unidad_nombre_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
