# Generated by Django 5.0.14 on 2026-07-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0008_backfill_unidad_nombre_abreviatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionsemanal',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20),
        ),
    ]
