# Generated by Django 5.0.14 on 2026-07-30 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0008_productoimagen_eliminar_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacion',
            name='fk_familia',
            field=models.ForeignKey(blank=True, db_column='fk_familia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rassa.familia'),
        ),
    ]
