# Generated by Django 5.0.14 on 2026-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0008_productoimagen_eliminar_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
