# Generated by Django 5.0.14 on 2026-07-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0009_add_folio_to_pago'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('fk_pedido',), name='unique_pago_per_pedido'),
        ),
    ]
