# Generated by Django 5.0.14 on 2026-07-15 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0009_alter_publicacionsemanal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosemanal',
            name='fk_producto',
            field=models.ForeignKey(db_column='fk_producto', on_delete=django.db.models.deletion.PROTECT, to='rassa.producto'),
        ),
        migrations.AddConstraint(
            model_name='publicacionsemanal',
            constraint=models.UniqueConstraint(fields=('fk_agricultor', 'semana'), name='unique_agricultor_semana'),
        ),
    ]
