# Generated by Django 5.0.14 on 2026-07-15 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0009_localidad_estado_municipio_estado'),
        ('rassa', '0010_alter_productosemanal_fk_producto_and_more'),
    ]

    operations = [
    ]
