# Generated by Django 5.0.14 on 2026-07-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0010_pago_unique_pedido_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=20),
        ),
    ]
