# Generated by Django 5.0.14 on 2026-07-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0010_pago_unique_pedido_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pago',
            name='unique_pago_per_pedido',
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(fields=('fk_pedido',), name='unique_pago_per_pedido', nulls_distinct=False),
        ),
    ]
