# Generated by Django 5.0.14 on 2026-07-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0011_merge_0009_localidad_estado_and_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiausuario',
            name='fk_usuario',
            field=models.ForeignKey(db_column='fk_usuario', on_delete=django.db.models.deletion.CASCADE, to='rassa.usuario'),
        ),
    ]
