# Generated by Django 5.0.14 on 2026-07-29 00:08

from django.db import migrations, models


def set_default_folio(apps, schema_editor):
    Pago = apps.get_model("rassa", "Pago")
    nulls = Pago.objects.filter(folio__isnull=True).order_by("id_pago")
    for i, pago in enumerate(nulls, start=1):
        pago.folio = f"LEGACY-{i:04d}"
        pago.save(update_fields=["folio"])


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0011_pago_unique_pedido_nulls_distinct'),
    ]

    operations = [
        migrations.RunPython(set_default_folio, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='pago',
            name='folio',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
