# Generated by Django 5.0.14 on 2026-07-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0011_merge_0009_localidad_estado_and_publicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoimagen',
            options={'ordering': ['orden', 'id_imagen']},
        ),
        migrations.AddField(
            model_name='productoimagen',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
