# Generated by Django 5.0.14 on 2026-07-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0012_alter_productoimagen_options_productoimagen_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='archivo',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
