# Generated by Django 5.0.14 on 2026-07-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0012_alter_familiausuario_fk_usuario'),
        ('rassa', '0012_mensaje_editado'),
    ]

    operations = [
    ]
