# Generated by Django 5.0.14 on 2026-07-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0013_alter_producto_fk_categoria'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productoimagen',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('fk_producto',), name='unique_es_principal_per_producto'),
        ),
    ]
