# Generated by Django 5.0.14 on 2026-07-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0014_add_unique_es_principal_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoimagen',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
