# Generated by Django 5.0.14 on 2026-07-31 20:49

import django.db.models.deletion
from django.db import migrations, models


def eliminar_recolecciones_huerfanas(apps, schema_editor):
    """Elimina filas legacy con fk_agricultor NULL.

    El modelo previo (hasta 0014) permitía fk_agricultor NULL. El AlterField a
    null=False ejecuta ALTER COLUMN SET NOT NULL y fallaría con "column contains
    null values" si quedara UNA fila huérfana en prod. Se ELIMINAN y no se
    cancelan: una recolección sin agricultor es inválida (fk_agricultor es
    obligatorio a partir de 0015) y no hay historia que preservar; cancelarla
    además dejaría el NULL en pie sin resolver el SET NOT NULL.
    """
    Recoleccion = apps.get_model("rassa", "Recoleccion")
    huerfanas = Recoleccion.objects.filter(fk_agricultor__isnull=True)
    count = huerfanas.count()
    huerfanas.delete()
    print(f"  [0015] eliminadas {count} recolecciones huérfanas (fk_agricultor NULL)")


def verificar_recolecciones_sin_huerfanas(apps, schema_editor):
    """Guard previo al AlterField: aborta si quedara alguna fila huérfana.

    Por construcción eliminar_recolecciones_huerfanas ya las eliminó; este guard
    es la última barrera para que el SET NOT NULL falle con un mensaje claro y no
    con un críptico "column contains null values".
    """
    Recoleccion = apps.get_model("rassa", "Recoleccion")
    if Recoleccion.objects.filter(fk_agricultor__isnull=True).exists():
        raise RuntimeError(
            "Migración 0015: quedan recolecciones con fk_agricultor NULL y no se pudieron "
            "eliminar; revisa los datos antes de aplicar el SET NOT NULL."
        )


def cancelar_duplicados_legacy(apps, schema_editor):
    """Cancela duplicados legacy del par (fk_agricultor, fecha_recoleccion).

    El modelo previo no tenía el UniqueConstraint parcial; si quedan filas
    activas con el mismo par (fk_agricultor, fecha_recoleccion), el
    AddConstraint fallaría en migrate. Se conserva la fila ACTIVA más antigua
    (menor id_recoleccion entre las no canceladas) y se cancelan el resto de
    las activas: "cancelado" queda fuera del constraint parcial y no se pierde
    ningún registro activo.
    """
    from django.db.models import Count

    Recoleccion = apps.get_model("rassa", "Recoleccion")
    estados_activos = ["pendiente", "en_ruta", "recolectado"]
    duplicados = (
        Recoleccion.objects.filter(estado__in=estados_activos)
        .values("fk_agricultor", "fecha_recoleccion")
        .annotate(total=Count("id_recoleccion"))
        .filter(total__gt=1)
    )
    total_canceladas = 0
    for dup in duplicados:
        ids_activos = (
            Recoleccion.objects.filter(
                fk_agricultor=dup["fk_agricultor"],
                fecha_recoleccion=dup["fecha_recoleccion"],
                estado__in=estados_activos,
            )
            .order_by("id_recoleccion")
            .values_list("id_recoleccion", flat=True)
        )
        # conservar la fila activa más antigua (primer id), cancelar el resto de las activas
        # list() materializa los ids restantes: migración one-shot, volumen legacy acotado
        total_canceladas += Recoleccion.objects.filter(id_recoleccion__in=list(ids_activos[1:])).update(
            estado="cancelado"
        )
    if total_canceladas:
        print(f"  [0015] canceladas {total_canceladas} recolecciones duplicadas legacy")


class Migration(migrations.Migration):
    dependencies = [
        ("rassa", "0014_populate_conversacion_fk_familia"),
    ]

    operations = [
        migrations.RunPython(eliminar_recolecciones_huerfanas, migrations.RunPython.noop),
        migrations.RunPython(verificar_recolecciones_sin_huerfanas, migrations.RunPython.noop),
        migrations.RunPython(cancelar_duplicados_legacy, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recoleccion",
            name="fk_agricultor",
            field=models.ForeignKey(
                db_column="fk_agricultor", on_delete=django.db.models.deletion.PROTECT, to="rassa.usuario"
            ),
        ),
        migrations.AddConstraint(
            model_name="recoleccion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "cancelado"), _negated=True),
                fields=("fk_agricultor", "fecha_recoleccion"),
                name="uniq_recoleccion_activa_agricultor_fecha",
            ),
        ),
    ]
