# Generated by Django 5.0.14 on 2026-08-01 03:24
# Edited: dedup RunPython runs BEFORE AddConstraint so the partial unique
# constraint applies cleanly even if migration 0014 left duplicate active
# family conversations behind.

from django.db import migrations, models


def dedup_family_conversations(apps, schema_editor):
    """Keep one active conversation per family; archive the duplicates.

    For groups of Conversacion rows sharing fk_familia (NOT NULL) and estado=True,
    keep the smallest id_conversacion active and set estado=False on the rest.
    No-op when there are no duplicates.
    """
    Conversacion = apps.get_model("rassa", "Conversacion")
    rows = (
        Conversacion.objects.filter(fk_familia__isnull=False, estado=True)
        .values("fk_familia")
        .annotate(cuantos=models.Count("id_conversacion"))
    )
    for row in rows:
        if row["cuantos"] <= 1:
            continue
        keep = (
            Conversacion.objects.filter(fk_familia=row["fk_familia"], estado=True)
            .order_by("id_conversacion")
            .first()
        )
        Conversacion.objects.filter(fk_familia=row["fk_familia"], estado=True).exclude(
            pk=keep.pk
        ).update(estado=False)


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0014_populate_conversacion_fk_familia'),
    ]

    operations = [
        migrations.RunPython(dedup_family_conversations, migrations.RunPython.noop),
        migrations.AddField(
            model_name='integrante',
            name='rol',
            field=models.CharField(choices=[('miembro', 'Miembro'), ('admin', 'Admin')], default='miembro', max_length=10),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='nombre_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', True), ('fk_familia__isnull', False)), fields=('fk_familia',), name='unique_active_family_conversation'),
        ),
    ]