# Generated by Django 5.0.14 on 2026-07-31 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0014_populate_conversacion_fk_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoleccion',
            name='fk_agricultor',
            field=models.ForeignKey(db_column='fk_agricultor', on_delete=django.db.models.deletion.PROTECT, to='rassa.usuario'),
        ),
        migrations.AddConstraint(
            model_name='recoleccion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelado'), _negated=True), fields=('fk_agricultor', 'fecha_recoleccion'), name='uniq_recoleccion_activa_agricultor_fecha'),
        ),
    ]
