# Generated by Django 5.0.14 on 2026-07-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0013_merge_20260718_1323'),
        ('rassa', '0015_add_producto_imagen_drive_file_id'),
    ]

    operations = [
    ]
