# Generated by Django 5.0.14 on 2026-08-01 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0015_alter_recoleccion_fk_agricultor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEstadoRecoleccion',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('fk_cambiado_por', models.ForeignKey(blank=True, db_column='fk_cambiado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rassa.usuario')),
                ('fk_recoleccion', models.ForeignKey(db_column='fk_recoleccion', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='rassa.recoleccion')),
            ],
            options={
                'db_table': 'historial_estado_recoleccion',
                'ordering': ['id_historial'],
            },
        ),
    ]
