# Generated by Django 5.0.14 on 2026-08-01 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0015_corte_add_fk_vendedor_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corte',
            options={'ordering': ['-fecha']},
        ),
    ]
