# Generated by Django 5.0.14 on 2026-07-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0015_productoimagen_squash_and_drive_file_id'),
        ('rassa', '0016_merge_20260719_1534'),
    ]

    operations = [
    ]
