# Generated by Django 5.0.14 on 2026-08-04 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rassa", "0016_alter_corte_options"),
        ("rassa", "0017_merge_chat_recoleccion"),
    ]

    operations = []
