# Generated by Django 5.0.14 on 2026-08-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0018_merge_20260803_1739'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='corte',
            name='unique_corte_vendedor_fecha',
        ),
        migrations.AlterField(
            model_name='corte',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, help_text='Snapshot de monto_real - monto_teorico al crear; no se actualiza con pagos posteriores.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='corte',
            name='monto_teorico',
            field=models.DecimalField(decimal_places=2, help_text='Snapshot calculado al crear el corte; no se actualiza con pagos posteriores.', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='corte',
            constraint=models.UniqueConstraint(condition=models.Q(('fk_vendedor__isnull', False)), fields=('fk_vendedor', 'fecha'), name='unique_corte_vendedor_fecha'),
        ),
    ]
