# Generated by Django 5.0.14 on 2026-08-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0014_populate_conversacion_fk_familia'),
        ('rassa', '0018_pago_unique_pedido_allow_null_distinct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="liquidacion",
            constraint=models.UniqueConstraint(
                condition=models.Q(estado__in=["pendiente", "parcial"]),
                fields=("fk_agricultor", "periodo_inicio", "periodo_fin"),
                name="unique_liquidacion_agricultor_periodo_activo",
            ),
        ),
    ]
