# Generated by Django 5.0.14 on 2026-08-04 02:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0019_remove_corte_unique_corte_vendedor_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corte',
            name='fecha',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
