# Generated by Django 5.0.14 on 2026-08-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0020_liquidacion_venta'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'parcial'])), fields=('fk_agricultor', 'periodo_inicio', 'periodo_fin'), name='unique_liquidacion_agricultor_periodo_activo'),
        ),
    ]
