# Generated by Django 5.0.14 on 2026-08-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0021_liquidacion_unique_liquidacion_agricultor_periodo_activo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='liquidacion',
            name='unique_liquidacion_agricultor_periodo_activo',
        ),
        migrations.AddField(
            model_name='liquidacion',
            name='tasa_comision',
            field=models.DecimalField(decimal_places=4, default=0.1, max_digits=5),
        ),
        migrations.AddConstraint(
            model_name='liquidacion',
            constraint=models.UniqueConstraint(fields=('fk_agricultor', 'periodo_inicio', 'periodo_fin'), name='unique_liquidacion_agricultor_periodo'),
        ),
    ]
