# Generated by Django 5.0.14 on 2026-08-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0015_chat_familia_fields'),
        ('rassa', '0022_remove_liquidacion_unique_liquidacion_agricultor_periodo_activo_and_more'),
    ]

    operations = [
    ]
