# Generated by Django 5.0.14 on 2026-08-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0017_merge_chat_recoleccion'),
        ('rassa', '0023_merge_20260803_1208'),
    ]

    operations = [
    ]
