# Generated by Django 5.0.14 on 2026-08-04 05:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0024_merge_20260803_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='tasa_comision',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), max_digits=5),
        ),
    ]
