# Generated by Django 5.0.14 on 2026-08-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0020_alter_corte_fecha'),
        ('rassa', '0025_alter_liquidacion_tasa_comision'),
    ]

    operations = [
    ]
