# Generated by Django 5.0.14 on 2026-08-05 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0026_merge_20260804_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='merma',
            name='fk_pedido',
            field=models.ForeignKey(blank=True, db_column='fk_pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mermas', to='rassa.pedidocabecera'),
        ),
    ]
