# Generated by Django 5.0.14 on 2026-08-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rassa', '0027_add_fk_pedido_to_merma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionmerma',
            name='decision',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='merma',
            index=models.Index(fields=['fk_pedido'], name='merma_fk_pedi_737a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='merma',
            index=models.Index(fields=['creado_en'], name='merma_creado__e1bb8d_idx'),
        ),
        migrations.AddIndex(
            model_name='merma',
            index=models.Index(fields=['fk_producto_semanal'], name='merma_fk_prod_ae7134_idx'),
        ),
        migrations.AddIndex(
            model_name='merma',
            index=models.Index(fields=['fk_decision'], name='merma_fk_deci_745a25_idx'),
        ),
    ]
